site_name: My Docs
theme:
  name: material
  language: en
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs       # 启用选项卡式导航
    - navigation.instant    # 启用即时加载
    - toc.integrate         # 在页面侧边集成目录
    - search.suggest        # 启用搜索建议
    - search.highlight      # 启用搜索结果高亮

