site_name: Pigasso's Web
site_author: 'Pigasso'
site_url: 'https://pigassooo.github.io/my-blog/'
repo_url: 'https://github.com/Pigassooo'

theme:
  custom_dir: docs/overrides
  name: material
  language: en
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: 'images/favicon.png'
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/p


  features:

    # - codehilite:  # 高亮代码块
    #     guess_lang: false
    - navigation.instant  # 实现页面的即时加载
    - navigation.instant.prefetch #即时预取
    - navigation.instant.progress #进度指示器
    - navigation.tabs  # 导航选项卡
    - navigation.tabs.sticky # 粘性导航选项卡
    - navigation.indexes  # 当部分没有内容时自动创建索引页面
    - navigation.sections  # 在侧边栏中使用章节
    - navigation.top  # 在页面顶部显示导航栏
    - toc.integrate  # 将目录(TOC)整合到文章侧边栏
    - toc.follow  # 目录随滚动高亮当前节
    - search.highlight  # 搜索结果高亮显示

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "\ue157"


plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  # - git-revision-date-localized:
  #     enable_creation_date: true
  - blog:
      blog_dir: blog
      post_dir: blog/posts
      categories: true
      categories_toc: true
      post_date_format: medium


extra:
  #语言栏
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 中文
      link: /zh/
      lang: zh
  #底侧连接
  social:
    - icon: material/email
      link: mailto:<1219632665@qq.com>
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCKX_MGD-u_ceV2XtNA6re3Q
    - icon: simple/reddit
      link: https://www.reddit.com/user/Pigasso_4ever/
    - icon: simple/bilibili
      link: https://space.bilibili.com/493000186?spm_id_from=333.1007.0.0
    - icon: simple/wechat
      link: https://s2.loli.net/2024/04/22/4GYzcikCTqmZonw.jpg

# 导航结构
nav:
  - Home: index.md
  - Notes:
    - notes/index.md
    - Computer English(processing): notes/computerEnglish.md
    - Useful Website:
      - Code: notes/website/code.md
    - Youtuber:
      - Coder: notes/youtuber/coder.md
  - Blog:
    - blog/index.md
  - Reprint:
    - reprint/index.md
    - Code: reprint/code/index.md
    - Articles: reprint/articles/index.md
    - Poetry:
      - reprint/poetry/index.md
      - CH: reprint/poetry/ch/index.md
      - EN: reprint/poetry/en/index.md
  - LoveStory:
    - loveStory/index.md
  - About: about.md