authors:
  pigasso:
    name: Pigasso
    description: Debug the world
    avatar: https://s2.loli.net/2024/04/21/yfBqSOLdnFVwo6l.jpg
  ch:
    name: CH
    description: 还没想好
    avatar: https://s2.loli.net/2024/04/21/yfBqSOLdnFVwo6l.jpg